window:
  size: # width, height (pixels)
    - 480
    - 640
  background_color: # red, green, blue, alpha (0-255)
    - 0
    - 0
    - 32
    - 255
  borderless: false
ball:
  color:
    - 0
    - 192
    - 192
    - 255
  highlight_color:
    - 255
    - 255
    - 64
    - 255
  radius: 10
  margin: 5
  highlight_frames: 20
rhythm:
  base_frequency: 440
  notes: # frequencies in Hz
    - 220
    - 277.18
    - 293.66
    - 329.63
    - 440
    - 554.37
    - 659.25
    - 739.99
    - 880
    - 1108.73
    - 1174.66
    - 1318.51
    - 1661.22
  rhythm_duration: 0.5 # time in seconds for first note to oscillate once
  base_sound: media/a440pluck.wav
mixer:
  frequency: 44100
  size: -16
  channels: 1
